name: movie_quiz_bloc
description: "IMDb Movie Quiz"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  bloc: ^8.1.3
  bloc_concurrency: ^0.2.4
  cached_network_image: ^3.3.1
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  freezed_annotation: ^2.4.1
  go_router: ^14.2.0
  http: ^1.2.1
  stream_transform: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.11
  freezed: ^2.5.2

flutter:
  uses-material-design: true
